config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :projects do
      get :send_invitation
      resources :tickets do 
        post :change_status
      end
    collection do 
      get :accept_invitation
    end
  end 
  get 'login', to: 'sessions#home'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/', to: 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      can :manage, user.projects
      # can :manage, user.projects.map{|project| project.tickets}
      can :manage, user.projects.map(&:tickets)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :tickets, dependent: :destroy
  
  validates :name , presence: true 
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  belongs_to :ticket_status, optional: true
  
  validates :title, presence: true

  after_create :set_ticket_status 

  def set_ticket_status
    status = TicketStatus.find_by_name("ToDo")
    self.update(ticket_status_id: status.id)
    
  end
end

app/models/ticket_status.rb
class TicketStatus < ApplicationRecord
  has_many :tickets
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates  :email, uniqueness: true, presence: true
  validates :first_name, presence: true
  has_and_belongs_to_many :projects
  
  def name=(value)
    return nil if value.blank?
    self.first_name, self.last_name = value.split(" ")
  end

  def name 
    return nil if self.first_name.blank?
    "#{self.first_name} #{self.last_name}"
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?
  include ApplicationHelper

  rescue_from Exception do |exception|
    if exception.is_a?(CanCan::AccessDenied)   
      redirect_to projects_path
    else
      Rails.logger.fatal("#{exception.message} ----- #{exception.backtrace}")
      render file: "#{Rails.root}/public/500.html", layout: false
    end
  end


  def current_user    
    User.find_by(id: session[:user_id])  
  end

  def logged_in?     
    !current_user.nil?  
  end

  def authorized
    redirect_to '/login' unless logged_in?
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource only: [:show, :destroy]
  before_action :fetch_project, only: [:show, :destroy]

  def index
    @projects =  current_user.projects
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    unless @project.errors.blank?
      respond_to do |format|
        format.js
      end
    else 
      @project.users << current_user
      redirect_to project_path(@project)
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end 

  def send_invitation
    project = Project.find(params[:project_id])
    user = current_user
    params[:users].each do |email|
      token = encode({email: email, project_id: params[:project_id]})
      to = User.find_by_email(email)
      InvitationMailer.send_project_invitation(user,email, token, project.name).deliver_now unless(project.users.include?(to))
    end
    redirect_to project_path(project)
  end

  def accept_invitation
    decoded_token = decode(params[:t]).first
    user = User.find_by_email(decoded_token["email"])
    project = Project.find(decoded_token["project_id"])
    if project.present?
      project.users << user  if(user == current_user && !user.projects.include?(project))
    end 
    redirect_to project_path(project)
  end 

  private

    def fetch_project
      @project = Project.find(params[:id])
    end 

    def project_params
      params.require(:project).permit(:name)
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :home]

  
  def home
    redirect_to projects_path if logged_in? 
  end

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
       redirect_to projects_path
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def login
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :fetch_ticket, only: [:show, :destroy, :edit, :update]


  def show
  end 

  def create
    @ticket = Ticket.create(ticket_params)
    if @ticket.errors.blank?
      redirect_to project_path(id: params[:project_id])
    else 
      respond_to do |format|
        format.js {render action: "errors"}
      end
    end
  end

  def edit
  end

  def update
    @ticket.update(ticket_params)
    if @ticket.errors.blank?
      redirect_to project_path(id: params[:project_id])
    else 
      respond_to do |format|
        format.js {render action: "errors"}
      end
    end
  end

  def destroy
    @ticket.destroy
  end

  def change_status
    @ticket = Ticket.find(params[:ticket_id])
    @ticket.update(ticket_status_id: params[:status_id])
    redirect_to project_path(id: params[:project_id])
  end

  private 
    def fetch_ticket
      @ticket = Ticket.find(params[:id])
    end 

    def ticket_params
      params.require(:ticket).permit(:title, :ticket_status_id, :descrition, :project_id)
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.errors.present?
      respond_to do |format|
        format.js
      end
    else 
      session[:user_id] = @user.id
      redirect_to projects_path  
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def encode(payload)
    JWT.encode(payload, Rails.application.secret_key_base)
  end

  def decode(token)
    JWT.decode(token, Rails.application.secret_key_base , true, algorithm: 'HS256')
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sidebar.html.erb
<div class="s-layout">
<!-- Sidebar -->
<div class="s-layout__sidebar">
  <a class="s-sidebar__trigger" href="#0">
     <i class="fa fa-bars"></i>
  </a>

  <nav class="s-sidebar__nav">
     <ul>
        <li class= "<%= "active" if params[:controller] == "projects"%>">
           <%=link_to  projects_path, class:"s-sidebar__nav-link" do%>
            <i class="fa fa-th-large"></i><em>Projects</em>
          <%end%>
        </li>
        <li class= "<%= "active" if params[:controller] == "users"%>">
           <%=link_to "#", class:"s-sidebar__nav-link" do %>
             <i class="fa fa-user"></i><em>My Profile</em>
            <%end%>
        </li>
        <li class= "<%= "active" if params[:controller] == "sessions"%>">
           <%=link_to logout_path, method: :delete, class:"s-sidebar__nav-link" do %>
              <i class="fa fa-sign-out"></i><em>Sign out</em>
           <%end%>
        </li>
     </ul>
  </nav>
</div>

<!-- Content -->
<main class="s-layout__content">
 <%=yield%>
</main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoftwareTicktingSys</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  </head>
  <body>
    <%if ["sessions", "users"].include?(params[:controller])%>
      <%= yield %>
    <%else%>
      <div class='sidebar-layout'>
        <%= render partial: "layouts/sidebar.html.erb"%>
      </div>
    <%end%>
  </body>
</html>

app/views/projects/_form.html.haml
- url = project.new_record? ?  projects_path  : project_path 

.modal-dialog
  .modal-content
    .modal-header
      %h4.modal-title
        Add Project
      %span{type: "button", class:"close" , 'data-dismiss': "modal"}
        &times;
    = form_for project, url: url, remote: true do |f|
      .modal-body
        .form-group
          .col-md-12
            = f.label :name 
          .col-md-12
            = f.text_field :name, placeholder: "Name", class: "mt-3 w-100 name"
      .modal-footer
        %button{type: "submit", class: "btn btn-primary"}
          Save
        %button{type: "button", class: "btn btn-dark", 'data-dismiss': "modal"}
          Close      

app/views/projects/create.js.erb
<%@project.errors.each do |field| %>
  $(".<%=field.to_s%>").addClass("invalid-input");
<%end%>

app/views/projects/index.html.haml
.row
  .col-md-12.col-sm-12
    .p-5.mt-5
      .section
        %h2.collpase.pointer
          %i.fa.fa-caret-down
          = "Projects(#{@projects.size})"
        .content
          .row
            .col-md-12
              %button.pull-right.display-modal{type: "button", 'data-toggle': "modal", "data-target": "#addProject", class: "btn btn-link"}
                %small
                  %i.fa.fa-plus
                  Add Project
              .modal{id:"addProject", role: "dialog"}
                =render partial: "form", locals:{project: Project.new}

          - if @projects.blank?
            .col-md-12
              %small There are no projects
          
          - @projects.each do |project|
            .row.p-2
              .col-sm-12.col-md-12.border
                .p-2  
                  =link_to project.name, project_path(project), class: "btn-link"
                  %i.fa.fa-trash.pull-right.pointer.color-red{'data-toggle': "modal", "data-target": "#deleteProject"}
                  .modal#deleteProject
                    .modal-dialog
                      .modal-content
                        .modal-header
                          %h4.modal-title
                            Delete porject
                          %span{type: "button", class:"close" , 'data-dismiss': "modal"}
                            &times;
                        .modal-body
                          Are you sure you want to delete the project? 
                        .modal-footer
                          = link_to "Delete", project_path(project), method: :delete, class:"btn btn-primary" 
                          %button{type: "button", class: "btn btn-dark", 'data-dismiss': "modal"}
                            Close                       
                                                    

app/views/projects/show.html.haml
.row.project-page
  .col-md-12.col-sm-12
    .p-5.mt-5
      .section
        %h2.collpase.pointer
          %i.fa.fa-caret-down
          = @project.name
        .content
          .row.my-2
            .col-md-12
              %h6
                - users = @project.users.size-1
                = "Members:  you and #{users} #{"other".pluralize(users)}"
                .pull-right.small{'data-toggle': "modal", "data-target": "#addUserModal"}
                  %i.fa.fa-plus
                  Add user
                .modal#addUserModal
                  .modal-dialog
                    .modal-content
                      .modal-header
                        %h4.modal-title
                          Share with users
                        %span{type: "button", class:"close" , 'data-dismiss': "modal"}
                          &times;
                      = form_tag project_send_invitation_path(project_id: @project.id), method: :get do |f|
                        .modal-body
                          = select_tag :users, options_for_select([]), class: "select2 selected-user", multiple: true 
                          - @project.users.each do |user|
                            .row.border-top.mt-2.pt-2
                              .col-md-12.small
                                %i.fa.fa-user-o
                                =user.name 
                                %span.text-muted= user.email
                        .modal-footer
                          %button{type: "submit", class: "btn btn-primary send-invitation-button", disabled: true}
                            Done
                          %button{type: "button", class: "btn btn-dark", 'data-dismiss': "modal"}
                            Close  
          %h4
            Tickets
          = render partial: "tickets/tickets"

                

app/views/tickets/_form.html.haml
.modal-dialog.ticket-dialog
  .modal-content
    .modal-header
      %h4.modal-title
        Add Ticket
      %span{type: "button", class:"close" , 'data-dismiss': "modal"}
        &times;
    - url = ticket.new_record? ?  project_tickets_path(project_id: @project.id)  : project_ticket_path(project_id: @project.id, id:ticket.id) 
    = form_for ticket , url: url , remote: true do |f|
      .modal-body
        .form-group
          .row
            = f.hidden_field :project_id , value: @project.id
            .col-md-12
              = f.label :title
            .col-md-12
              = f.text_field :title, class: "w-100 title"
        .form-group.mt-3
          .row
            .col-md-12
              = f.label :descrition, "Description"
            .col-md-12
              = f.text_area :descrition , class: "w-100 ticket-description descrition"           
      .modal-footer
        %button{type: "submit", class: "btn btn-primary "}
          Add
        %button{type: "button", class: "btn btn-dark", 'data-dismiss': "modal"}
          Close  

app/views/tickets/_tickets.html.haml
- ticket_statuses = TicketStatus.pluck(:name, :id) 

.col-md-12.border-top
  .row.m-2.pointer{'data-toggle': "modal", "data-target": "#addTicket"}
    Add new Ticket
  .modal#addTicket
    =render partial: "tickets/form", locals:{ticket: Ticket.new}
- if @project.tickets.blank?
  .col-md-12.border-top
    .row.m-2
      There are no tickets
- @project.tickets.each do |ticket|
  .border-top{class: "ticket-row-#{ticket.id}"}
    .row.m-2
      .col-md-10.col-sm-8
        =link_to project_ticket_path(project_id:@project.id, id:ticket.id), method: :delete , remote: true do
          %i.fa.fa-trash.color-red
        %i.fa.fa-pencil.pointer{"data-target": "#editTicket#{ticket.id}", 'data-toggle': "modal"}
        .modal{id:"editTicket#{ticket.id}"}
          =render partial: "tickets/form", locals:{ticket: ticket}
        = ticket.title
      .col-md-2.col-sm-4
        .dropdown.pull-right
          .dropdown-toggle.pointer{"data-toggle": "dropdown"}
            =ticket.ticket_status.name
          .dropdown-menu
            - ticket_statuses.each do |status|
              - if ticket.ticket_status_id != status[1]
                =link_to "#{status[0]}", project_ticket_change_status_path(project_id: @project.id, status_id: status[1], ticket_id: ticket.id), method: :post, class: "dropdown-item"

app/views/tickets/destroy.js.erb
$(".ticket-row-<%=@ticket.id%>").remove();

app/views/tickets/errors.js.erb
$(".invalid-input").removeClass("invalid-input");
<%@ticket.errors.each do |field| %>
  $(".<%=field.to_s%>").addClass("invalid-input");
<%end%>

app/views/users/create.js.erb
$(".invalid-input").removeClass("invalid-input");
<%@user.errors.each do |field| %>
  $("input[er='<%=field.to_s%>']").addClass("invalid-input");
<%end%>

app/views/users/new.html.haml
.home-page
  .container
    .card
      .card-body
        .circle
        %header.my-hed.text-center
          %i.fa.fa-user-o
          %p
            SIGN UP
        .main-form.text-center
          = form_for @user, class: 'main-form text-center', remote: true do |f|
            .form-group.my-0
              %label.my-0
                %i.fa.fa-address-book.input-icon
                = f.text_field :name, class: "myInput", placeholder: "Full name", er: "first_name"
            .form-group.my-0
              %label.my-0
                %i.fa.fa-user.input-icon
                = f.text_field :email, class: "myInput", placeholder: "Email", er: "email"
            .form-group.my-0
              %label.my-0
                %i.fa.fa-lock.input-icon
                = f.text_field :password, class: "myInput", placeholder: "Password", type: "password", er: "password"
            .form-group.mt-5
              %label
                = submit_tag "Continue", class: "form-control button "
            .form-group.my-1
              %small 
                Already have an account?
                =link_to "/", class: "btn btn-link p-0" do
                  .my-0
                    %small Sign in